remote: true
experience_level:
  internship: false
  entry: true
  associate: false
  mid_senior_level: false
  director: false
  executive: false
job_types:
  full_time: true
  contract: false
  part_time: false
  temporary: false
  internship: false
  other: false
  volunteer: false
date:
  all_time: false
  month: true
  week: false
  24_hours: false
positions:
  - "Software Engineer"
  - "Backend Developer"
  - "Python Developer"
locations:
  - "Remote"
  - "United States"
  - "India"
location_blacklist:
  - Brazil
distance: 50
company_blacklist: []
title_blacklist: []